// Code generated by xgen. DO NOT EDIT.

package ofx

// GetMimeRequest is The OFX element "GETMIMERQ" is of type "GetMimeRequest"
type GetMimeRequest struct {
	URL *UrlType `xml:"URL"`
}

// GetMimeResponse is The OFX element "GETMIMERS" is of type "GetMimeResponse"
type GetMimeResponse struct {
	URL string `xml:"URL"`
}

// MailRequest is The OFX element "MAILRQ" is of type "MailRequest"
type MailRequest struct {
	MAIL *Mail `xml:"MAIL"`
}

// MailResponse is The OFX element "MAILRS" is of type "MailResponse"
type MailResponse struct {
	MAIL *Mail `xml:"MAIL"`
}
